### ISSUE TITLE
Nuget package Upgrade 1.1.3.1 to 1.1.4 failed to add reference

### ISSUE THREAD

**Issue by richardbartley** [scottksmith95/LINQKit#37]
Failed to add reference. The package 'LinqKit' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by Thorium** [comment]
This is probably due to modifications to solution model and package generation.
Ping @StefH

**Comment by StefH** [comment]
For which framework do you use LinqKit ?

**Comment by richardbartley** [comment]
.Net 4.5.1

**Comment by StefH** [comment]
Issue should be fixed, please checkout latest NuGet,

**Comment by richardbartley** [comment]
Thanks, will check out first thing tomorrow morning when back in office.

Great library, thanks 
Richard.

**Comment by orlandow** [comment]
I still have the issue with version `v1.1.5`

I'm using .net 4.5.2

**Comment by StefH** [comment]
please retry with https://www.nuget.org/packages/LinqKit/1.1.6

**Comment by orlandow** [comment]
It works now! thanks :+1:

**Comment by richardbartley** [comment]
Working for .Net 4.5.1 thanks.

**Comment by niemyjski** [comment]
We need to file a bug for this issue with nuget.. It will happen if you have a "frameworkAssemblies" section with non build time dependencies...

**Comment by StefH** [comment]
Hi @niemyjski you here?

Note that this issue was 'fixed' by removing the portable 4.5 target from the project.json

I think that
* the nuget is build wrongly ?
Or
* nuget has problems selecting the correct version when there is a portable 4.5 and a real 4.5 ?

**Comment by niemyjski** [comment]
Yeah, please comment on my issue. if you don't defined a real 4.5 package it will fallback to portable 4.5
